### ISSUE TITLE
BUG: rpc call for block level 1344062 is failing

### ISSUE THREAD

**Issue by davidrybar** [tezedge/tezedge#1057]
When running tezedge, there are many errors like "ERRO Failed to execute RPC function, reason: UnexpectedError { reason: "recursion limit exceeded at line 10758 column 73" }" when we try to get /chains/main/blocks/1344062 from rpc

We are using tezedge in a docker:
tezedge/tezedge:v2.0.0@sha256:3c7ea7158828b731044293699b1ac6e0ab6594cf0df27622be233a31bc33a629
--network=mainnet
--tezos-context-storage=irmin

Same issue appears on your tezedge instance where request never returns data:
https://master.dev.tezedge.com:8752/chains/main/blocks/1344062

**Comment by tizoc** [comment]
@davidrybar thanks for the report. The amount of metadata produced by that block may be hitting some limit, we will investigate.

**Comment by tizoc** [comment]
I think I found the cause of the issue, we should probably have a fix for it soon.

**Comment by tizoc** [comment]
Hi @davidrybar, v2.2.0 just got released and it includes the fix to this issue.

Our master server has not been re-deployed yet but you can see it here: http://develop.dev.tezedge.com:18732/chains/main/blocks/1344062
