### ISSUE TITLE
Import blockchain data from snapshot

### ISSUE THREAD

**Issue by 11qu1d** [tezedge/tezedge#919]
Hi,

I am trying to figure out what is the fastest way to bootstrap a Tezedge node from scratch. Using the Octez implementation we have the option to import the blockchain data from different types of snapshots (full or rolling), which is very handy when we need to spin up a node fast. Looking through the Tezedge docs I couldn't find anything on that. Would greatly appreciate if someone could point me in the right direction.

Thank you in advance.

**Comment by tizoc** [comment]
Hi @11qu1d. We don't have the same kind of snapshots Octez supports (yet), but you can  download a full archive snapshot that you can use with TezEdge from: http://snapshots.tezedge.com

Example:

```
wget -c -m -np -nH --cut-dirs=1 -R 'index.html*' http://snapshots.tezedge.com/tezedge_mainnet_20220115-111854_BM9UGxgrdciivoxBZvXs5vdaoNfdhK89iREWJ7kGqNFrUmU4urv/
```

Just one warning, it is quite big.

**Comment by 11qu1d** [comment]
Hi @tizoc, thanks for the quick reply. 

I am trying to setup with the persistent storage Dockerfile provided. Once the download is complete do I just bind mount the directory with the downloaded files under `/tmp/tezedge` inside the container or do I have to use any other docker options or commands when running it? Sorry for the many questions, just started using the software today.

Thanks

**Comment by tizoc** [comment]
@11qu1d oh, wait, in that case that snapshot will not work, because it uses Irmin. We don't have snapshots available for our context storage implementation yet. I may be able to provide you with one soon (even a smaller one that doesn't include the full history), but maybe not sooner than it would take for you to wait for the bootstrap to complete.

**Comment by 11qu1d** [comment]
Ah I see, not a problem. In that case do I need to use another dockerfile or there is another set of docker commands I should use?

**Comment by tizoc** [comment]
@11qu1d in that case you should just use the [main docker-compose.yml file](https://github.com/tezedge/tezedge/blob/master/docker-compose.yml).

And as you mentioned, you should mount the downloaded directory to `/tmp/tezedge` (you will probably want to modify it or create a copy, and add a `volumes:` entry under `node:`, something like:

```yaml
  node:
    image: tezedge/tezedge:v1.14.0
    # .... snip ....
    # ++++ ADDED ++++
    volumes:
      - "/path/to/snapshot/data:/tmp/tezedge"
```

**Comment by 11qu1d** [comment]
Thanks @tizoc, i switched to using `docker-compose.storage.irmin.yml` with the bind mount to `/tmp/tezedge` and things started working. Closing this issue.
